from . import account_account
from . import account_journal
from . import account_move
from . import account_cash
from . import cost_center
from . import exchange_rate
from . import res_partner
from . import res_company
from . import product
from . import stock_layer
from . import stock_consumption
from . import stock_movement
from . import purchase_order
from . import purchase_receipt
from . import purchase_bill
from . import purchase_advance
from . import purchase_payment
from . import purchase_return
from . import purchase_writeoff
from . import sale_order
from . import sale_delivery
from . import sale_invoice
from . import sale_advance
from . import sale_receipt
from . import sale_return
from . import sale_writeoff
from . import fixed_asset
from . import fixed_asset_report
from . import payroll
from . import stock_consume
from . import stock_opname
from . import account_closing
from . import demo_generator
from . import financial_report
from . import stock_report
from . import dashboard
